apiVersion: v1
kind: Service
metadata:
  name: feedback
  labels:
    run: feedback
spec:
  ports:
    - port: 3000
      targetPort: 8888
      protocol: TCP
  type: NodePort
  selector:
    run: feedback

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: feedback
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: feedback
  spec:
    containers:
      - name: feedback
        image: 963962/feedback
        ports:
          – containerPort: 8888
      - name: mongo
        image: mongo
        ports:
          - containerPort: 27017

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo
#   labels:
#     run: mongo
# spec:
#   ports:
#     - port: 27017
#       targetPort: 27017
#       protocol: TCP
  # selector:
  #   run: mongo

---
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: mongo
# spec:
#   template:
#     metadata:
#       labels:
#         run: mongo
#     spec:
#       containers:
#         - name: mongo
#           image: mongo
#           ports:
#             - containerPort: 27017
